### ISSUE TITLE
A Plugin To **NOT** Hide The Emoji Picker After Adding A Reaction/Emoji

### ISSUE THREAD

**Issue by RGBCube** [Aliucord/plugin-requests#1]
### Description
a plugin that makes it so the emoji picker (search) dosent hide when you pick an emoji

### More info
why? *i NEED to reaction wall in mobile*

---

- [x] I checked if this plugin wasn't already requested.

**Comment by RGBCube** [comment]
:xd1: :xd2: :xd3: :xd4: :xd5: :xd6: :xd7: :xd8: :xd9: :xd10: :xd11: :xd12: :xd13: :xd14: :xd15: :xd16: :xd17: :xd18: :xd19: :xd20:

**Comment by Vendicated** [comment]
this will be part of https://github.com/Vendicated/AliucordPlugins/blob/main/EmojiUtility once it releases. I will likely make it so that if you single tap the react button the menu will go away after reacting and if you double tap it will stay open

There's already an alpha build in my repo that implements this that you can use, but the plugin is nowhere near finished so don't expect it to be very polished.

**Comment by g1ZN7e9G** [comment]
should probably automatically delete the space too while you're at that

**Comment by Vendicated** [comment]
Done! https://github.com/Vendicated/AliucordPlugins/tree/main/EmojiUtility    

___
> should probably automatically delete the space too while you're at that

not currently a feature but i will add that too
