### ISSUE TITLE
Virustotal

### ISSUE THREAD

**Issue by hjroh0315** [Aliucord/plugin-requests#129]
### Discord Account

CrO4 2-#0010

### Plugin Description

Scan every link or file received in DMs with the VirusTotal API, and block the user when the link (or file) is found malicious. also scan each link in a server channel and append "(Safe)" / "(Unsafe)" to the link based on the result. optionally require the user to input their own token to prevent being ratelimited.

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Vendicated** [comment]
Checking files is redundant, as Discord already does this:
![image](https://user-images.githubusercontent.com/45497981/128258488-daf21e47-3947-4218-a088-ca11aaa09b44.png)

Checking links however could prove useful to avoid phishing links. The plugin could simply scrape virustotal which is easy and seems to have a very high tolerance (i tried like 40 times and am still not rate limited / captcha'd)

<details>
<summary>Minimal curl code for getting json data about an url for anyone who wants to make this:</summary>

```sh
curl https://www.virustotal.com/ui/search \
    --get \
    --data-urlencode "limit=20" \
    --data-urlencode "relationships[comment]=author,item" \
    --data-urlencode "query=$URL" \
    -H "Content-Type: application/json" \
    -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Firefox' \
    -H 'X-Tool: vt-ui-main' \
    -H "X-VT-Anti-Abuse-Header: uwu" \
    -H 'Accept-Ianguage: en-US,en;q=0.9,es;q=0.8'
```
</details>

**Comment by Vendicated** [comment]
This plugin does not fulfil all requested points due to limitations and also what i mentioned before, so I'm not sure if this satisfies you but I made this. It checks links after opening (and displays result in) the "Are you sure you want to open this link" modal

https://github.com/Vendicated/AliucordPlugins/tree/main/CheckLinks

![Screen](https://cdn.discordapp.com/attachments/852332951542956052/873245670734200832/unknown.png)

**Comment by hjroh0315** [comment]
this is great you can close
