### ISSUE TITLE
Hidden Message

### ISSUE THREAD

**Issue by CDotNightHawk** [Aliucord/plugin-requests#201]
### Discord Account

NightHawk#9999

### Plugin Description

Port over of Apate, better discord plugin - new. Can see the encrypted messages on pc and android.

### Go into more detail...

Like Apate, the message is encypted and can't be seen without the plugin.
![image](https://user-images.githubusercontent.com/64332203/131266157-47f89541-41fe-461d-8161-33bd509baa2b.png) ![image](https://user-images.githubusercontent.com/64332203/131266159-2808e288-f89c-41bb-a88a-d20dc8f9afef.png)

![image](https://user-images.githubusercontent.com/64332203/131266168-cdcda20d-9343-4d2a-95c3-bed86e4118ca.png)

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by UA-Archiver** [comment]
Small Question, Would it be better to port SimpleDiscordCrypt rather than Apate?
Link to SDC - https://gitlab.com/An0/SimpleDiscordCrypt

Simple reason - More Platforms, Dev wanted to update his Android Discord version

Long - 
I say this as SDC has more platforms supported.

- Browsers (extension or Userscript), 
- Normal Discord -
    - Directly hooking,
    - BD (PC using compatibility layer) 
    - Also LightCord and few other ones as well
- Android via Modded APK also exists but its heavily outdated

The Dev wants to update and work on an Aliucord plugin for ease rather than mod from ground up

AFIK, the dev is in the Aliucord server, so if another Aliucord Plugin Developer can help them, it could speed up the process

**Comment by Reinified** [comment]
This is done, check out [InvisibleMessages](https://github.com/mantikafasi/AliucordPlugins/blob/builds/InvisibleMessages.zip)
