### ISSUE TITLE
unistall option

### ISSUE THREAD

**Issue by harrynotfound** [Aliucord/plugin-requests#516]
### Discord Account

mr.harry#8366

### Plugin Description

a plugin that could that could have a unistall option with the plugins that you already have , like where you get the reinstall option unistall option there too , maybe it can be just a normal aliucord feature too 

### Go into more detail...

i wont want to have such a dumb plugin but yeah it shld probably be there as since it can make stuff ezier 

### Request Agreement

- [X] I did indeed check to make sure my plugin request is original!

**Comment by hairyfred** [comment]
You can reinstall a plugin easily by going to plugins list, holding install, then pressing uninstall then install?
Me and others are very confused with what you want for this plugin request.
Can you try and phrase it differently, potentially a mock up of what visually you mean?
Closing this for now until clarification of what this plugin is actually supposed to be

**Comment by WhenFreedom** [comment]
I think I understand what you mean... So you want an "uninstall" button to appear within the context menu where it would say only "reinstall plugin" usually.

But this would only apply to the channel "#new-plugins" because in "#plugins-list" you are just welcomed with the PluginDownloader, and there you are able to install/uninstall plugins regardless. 

Can easily just search for the plugin within your plugins list if you want to uninstall it though.

**Comment by Vendicated** [comment]
Even then that should be a request to Plugin Downloader which is a coreplugin, thus this is the wrong place to request. Anyway I dont see the purpose of this? Just use plugins page lol
