### ISSUE TITLE
Copy part of text from any message

### ISSUE THREAD

**Issue by MrArhynaH** [Aliucord/plugin-requests#643]
### Plugin Description

A plugin that copies a certain part of a message from sent messages. 
![Screenshot_20220219-233015_Chrome](https://user-images.githubusercontent.com/86986719/154812106-1908beed-1ab8-452b-8852-76b924f5123d.jpg)

### Go into more detail...

As copying whole message is the only option when copying text, it is super annoying to copy a certain phrase, emoji or anything from a long message. So, a plugin to copy only the highlighted part would be cool. [I did search with a few keywords related to this and couldn't find any request so I hope it's original]

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by zt64** [comment]
ViewRaw can do this

**Comment by MrArhynaH** [comment]
I know but that's more pain and it's much easier this way.

**Comment by ItzOnlyAnimal** [comment]
how? view raw is exactly what ur describing

**Comment by MrArhynaH** [comment]
Because I am not directly copying but instead I am holding the message, tapping view raw, holding the certain part of the raw message and then copying. I mean, it does the job but it could be done better with that described plugin. (i think?)

**Comment by ItzOnlyAnimal** [comment]
Hm ok that would probably be better to suggest as an update to view raw if anything. another plugin for the same thing doesnt sound real useful

**Comment by MrArhynaH** [comment]
It probably is better that way but I didn't know where to request for something like this and didn't really think that it shares the same purpose as view raw. It felt more like view raw is just doing the job in its process rather than being made certainly for it.

**Comment by Hades785** [comment]
The only way I see it working is having a plug-in give you an option to open a context to copy text in it.... So just like View Raw but w/o the other info.
Making it so you could select text in the app, if at all possible, would break how you interact (long press) w/ messages so... yeah.

**Comment by MrArhynaH** [comment]
I am not a coder so I don't know if it's possible or not but in my sense/idea, it could be the viewraw plugin that has the viewraw option on the very right of each message and upon tapping, it will switch the message box into message content selection. I might sound crazy to people who know how to code but it's just an idea anyway.

**Comment by WhenFreedom** [comment]
Actually I know a possible solution. And this already exists as a plugin. It's not exactly what you want but it's close enough. Similar to ViewRaw, EditMessagesLocally actually works really well for this, even though it's not the purpose of the plugin. When you click on "Edit Message Locally" in the context menu, the entire message appears in the chatbox allowing you to copy parts, as well as edit on the go. 

The plugin also makes it extremely easy if for example you want to copy multiple chunks of the message. Easy solution would be to cut out the chunks of the message you don't want and to keep the parts you want... Which is somewhat better than having the ability of copying from messages, it will save you time.

And when you're done copying/manipulating the data you want from the message? Simply copy, press the "x" to cancel, or you can save the message locally so you don't lose the data straight away if you did in fact remove chunks of the message

It does have a similar function to ViewRaw though. If the message contains markup to make text bold for example, the asterisks still appear. 
It's also somewhat better for copying than ViewRaw because you don't have all that information that might not be necessary, and on the plus, emojis don't appear as "\u003c:cryPepe:911967085180125235\u003e", which is how they appear with ViewRaw.  Instead emojis appear like ":cryPepe:". 

Only problem with EditMessagesLocally is that it does not work in channels where you do not have permission to send messages. If the ability to edit messages in channels where you do not have permission to message, I think the plugin would be absolutely flawless. 

But yeah, I don't think a new plugin is required if there already is solutions with existing plugins.
